package seoyunnie.pokeprotocol.network.message;

public enum MessageType {
    HANDSHAKE_REQUEST,
    HANDSHAKE_RESPONSE,
    SPECTATOR_REQUEST,
    BATTLE_SETUP,
    ATTACK_ANNOUNCE,
    DEFENSE_ANNOUNCE,
    CALCULATION_REPORT,
    CALCULATION_CONFIRM,
    RESOLUTION_REQUEST,
    GAME_OVER,
    CHAT_MESSAGE;
}
